version: "3.2"
services:
  backend:
    build: ./api
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=hello_world.settings.development
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    command: npm start